config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root "items#index"

  resources :cards, only: [:new, :create, :edit, :show, :destroy, :update]
  
  resources :my_pages, only: [:show]

  resources :items do
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  # has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/delivery_day.rb
class DeliveryDay < ActiveHash::Base
  self.data = [
                {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
              ]
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
                {id: 1, name: '送料込み（配送者負担）'}, {id: 2, name: '着払い（購入者負担）'}
              ]
end

app/models/delivery_style.rb
class DeliveryStyle < ApplicationRecord
  # has_many :items
end

app/models/delivery_way.rb
class DeliveryWay < ActiveHash::Base
  self.data = [
                {id: 1, name: '未定'}, {id: 2, name: 'らくらくメルカリ便'}, {id: 3, name: 'ゆうメール'},
                {id: 4, name: 'レターパック'}, {id: 5, name: '普通郵便（定形、定形外'}, {id: 6, name: 'クロネコヤマト'},
                {id: 7, name: 'ゆうパック'}, {id: 8, name: 'クリックポスト'}, {id: 9, name: 'ゆうパケット'}
              ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader  :src  , ImageUploader
  belongs_to      :item , optional: true
  validates       :item , presence: true, on: :update # on :updateはupdateアクションの時のみにバリデーション検証が実行されるもの
  validates       :src  , presence: true, on: :update 
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  belongs_to :category, optional: true #nullを許可

  belongs_to :user


  # fields_forメソッドを利用する際に、親モデルの中に書く必要があるメソッド。引数として子モデルの名前を書く。
  # allow_destroy: trueで親のレコードが削除された場合に、関連付いている子のレコードも一緒に削除してくれます
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank

  validates :name,               presence: true, length: { maximum: 40 }
  validates :description,        presence: true, length: { maximum: 1000 }
  validates :price,              presence: true, numericality: { only_integr: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :business_result,    presence: true
  validates :category_id,        presence: true
  validates :prefecture_id,      presence: true
  validates :delivery_fee_id,    presence: true
  validates :delivery_way_id,    presence: true
  validates :delivery_day_id,    presence: true
  validates :item_condition_id,  presence: true
  validates :status,             presence: true
  validates :images,             presence: true, on: :update # on :updateはupdateアクションの時のみにバリデーション検証が実行されるもの
  

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :delivery_way
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_day
  belongs_to_active_hash :item_condition

  

end

app/models/item_condition.rb
class ItemCondition < ActiveHash::Base
  self.data = [
                {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れ無し'},
                {id: 4, name: 'やや傷や汚れ有り'}, {id: 5, name: '傷や汚れ有り'}, {id: 6, name: '全体的に状態が悪い'}
              ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :email, presence: true
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true
  validates :birthday, presence: true

   # 半角以外の正規表現      
  validates :family_name, :first_name,format: {
    with: /[^ -~｡-ﾟ]+/,
    message: "全角のみで入力して下さい"
  }

  validates :family_name_kana, :first_name_kana,format: {
    with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/,
    message: "全角カタカナのみで入力して下さい"
  }


  has_many :items

  has_one :card

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def top
  end

  def step1
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    
    # (
    #   nickname: session[:nickname],
    #   email: session[:email],
    #   password: session[:password],
    #   password_confirmation: session[:password_confirmation],
    #   family_name: session[:family_name],
    #   first_name: session[:first_name],
    #   family_name_kana: session[:family_name_kana],
    #   first_name_kana: session[:first_name_kana],
    #   birthday: session[:birthday],
    #   phone_number: session[:phone_number],
    # )
    if @user.save
      # session[:id] = @user.id
      redirect_to done_signup_index_path
    else
      render '/signup/step1'
    end
  end
  
  def done
    # sign_in User.find(user:id) unless user_signed_in?
  end
  
  private
   # 許可するキーを設定
    def user_params
      params.require(:user).permit(
        :nickname,
        :email,
        :password,
        :password_confirmation,
        :family_name,
        :first_name,
        :family_name_kana,
        :first_name_kana,
        :birthday,
        :phone_number,
      )
    end


end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/sign_up/new.html.haml
%h2 Sign up
= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
  = render "devise/shared/error_messages", resource: resource
  .field
    = f.label :ニックネーム
    %br/
    = f.text_field :nickname, autofocus: true, autocomplete: "nickname"
  .field
    = f.label :email
    %br/
    = f.email_field :email, autofocus: true, autocomplete: "email"
  .field
    = f.label :password
    - if @minimum_password_length
      %em
        (#{@minimum_password_length} characters minimum)
    %br/
    = f.password_field :password, autocomplete: "new-password"
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation, autocomplete: "new-password"
  .field
    = f.label :お名前（全角）
    %br/
    = f.text_field :family_name, autofocus: true, autocomplete: "family_name"
  .field
    = f.label :お名前（全角）
    %br/
    = f.text_field :first_name, autofocus: true, autocomplete: "first_name"
  .field
    = f.label :お名前カナ（全角）
    %br/
    = f.text_field :family_name_kana, autofocus: true, autocomplete: "family_name_kana"
  .field
    = f.label :お名前（全角）
    %br/
    = f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana"
  .field
    = f.label :生年月日
    %br/
    = f.date_select(                  |
      :birthday,                      |
      start_year: 1930,               |
      end_year: (Time.now.year - 18), |
      default: Date.new(1989, 1, 1))  |
    \%&gt;
  .field
    = f.label :携帯電話
    %br/
    = f.telephone_field :phone_number, autofocus: true, autocomplete: "phone_number"
  .actions
    = f.submit "Sign up"
= render "devise/shared/links"

app/views/sign_up/sign_in.html.haml
.account-page
  .account__header
    = link_to image_tag("logo.png", class: "account__header__test-image"), root_path
  .loginMain
    .loginMain__registration
      .loginMain__registration__text
        アカウントをお持ちでない方はこちら
      = link_to "#", class:"link" do
        .loginMain__registration__btn
          新規会員登録
    .loginMain__sns
      = link_to "#", class: "account__center__url--facebook" do
        .account__center__url--btn_facebook
          = icon('fab', 'facebook-square')
          Facebookで登録する
      = link_to "#", class: "account__center__url--google" do
        .account__center__url--btn_google
          = icon('fab', 'google')
          Googleで登録する
    .loginMain__mail
      = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
        .loginMain__mail__field
          = f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "メールアドレス", class:"form"
        .loginMain__mail__field
          = f.password_field :password, autocomplete: "current-password", placeholder: "パスワード", class:"form"
        .loginMain__mail__submit
          = f.submit "ログイン", class:"loginMain__mail__submit-btn"
        = link_to "パスワードをお忘れの方", new_password_path(resource_name), class: "loginMain__mail--fogetPass"
  .account__footer
    .account__footer--top
      = link_to "プライバシーポリシー" , "#", class: "account__footer--top--1"
      = link_to "FURIMA利用規約" , "#", class: "account__footer--top--2"
      = link_to "特定商取引に関する表記" , "#", class: "account__footer--top--3"
    .account__footer--logo
      = link_to image_tag("logo-white.png", class: "account__footer--logo--test1-image"),"#"
    .account__footer--name
      © FURIMA, Inc.

app/views/sign_up/top_sinup.html.haml
.account-page
  .account__header
    = link_to image_tag("logo.png", class: "account__header__test-image"),"#"
  .account__center
    .account__center__title
      新規会員登録
    .account__center__url
      = link_to "#", class: "account__center__url--envelope" do
        .account__center__url--btn_mail
          = icon('far', 'envelope')
          メールアドレスで登録する
      = link_to "#", class: "account__center__url--facebook" do
        .account__center__url--btn_facebook
          = icon('fab', 'facebook-square')
          Facebookで登録する
      = link_to "#", class: "account__center__url--google" do
        .account__center__url--btn_google
          = icon('fab', 'google')
          Googleで登録する
  .account__footer
    .account__footer--top
      = link_to "プライバシーポリシー" , "#", class: "account__footer--top--1"
      = link_to "FURIMA利用規約" , "#", class: "account__footer--top--2"
      = link_to "特定商取引に関する表記" , "#", class: "account__footer--top--3"
    .account__footer--logo
      = link_to image_tag("logo-white.png", class: "account__footer--logo--test1-image"),"#"
    .account__footer--name
      © FURIMA, Inc.

app/views/signup/done.html.haml
完了

app/views/signup/top.html.haml
.account-page
  .account__header
    = link_to image_tag("logo.png", class: "account__header__test-image"),"#"
  .account__center
    .account__center__title
      新規会員登録
    .account__center__url
      = link_to step1_signup_index_path, class: "account__center__url--envelope" do
        .account__center__url--btn_mail
          = icon('far', 'envelope')
          メールアドレスで登録する
      = link_to "#", class: "account__center__url--facebook" do
        .account__center__url--btn_facebook
          = icon('fab', 'facebook-square')
          Facebookで登録する
      = link_to "#", class: "account__center__url--google" do
        .account__center__url--btn_google
          = icon('fab', 'google')
          Googleで登録する
  .account__footer
    .account__footer--top
      = link_to "プライバシーポリシー" , "#", class: "account__footer--top--1"
      = link_to "FURIMA利用規約" , "#", class: "account__footer--top--2"
      = link_to "特定商取引に関する表記" , "#", class: "account__footer--top--3"
    .account__footer--logo
      = link_to image_tag("logo-white.png", class: "account__footer--logo--test1-image"),"#"
    .account__footer--name
      © FURIMA, Inc.