config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root "items#index"

  resources :cards, only: [:new, :create, :edit, :show, :destroy, :update]
  
  resources :my_pages, only: [:show]

  resources :items do
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  belongs_to :category, optional: true #nullを許可

  belongs_to :user


  # fields_forメソッドを利用する際に、親モデルの中に書く必要があるメソッド。引数として子モデルの名前を書く。
  # allow_destroy: trueで親のレコードが削除された場合に、関連付いている子のレコードも一緒に削除してくれます
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank

  validates :name,               presence: true, length: { maximum: 40 }
  validates :description,        presence: true, length: { maximum: 1000 }
  validates :price,              presence: true, numericality: { only_integr: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :business_result,    presence: true
  validates :category_id,        presence: true
  validates :prefecture_id,      presence: true
  validates :delivery_fee_id,    presence: true
  validates :delivery_way_id,    presence: true
  validates :delivery_day_id,    presence: true
  validates :item_condition_id,  presence: true
  validates :status,             presence: true
  validates :images,             presence: true, on: :update # on :updateはupdateアクションの時のみにバリデーション検証が実行されるもの
  

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :delivery_way
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_day
  belongs_to_active_hash :item_condition

  

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  
  def index
    @items = Item.last(5)
  end


  def new
    @item = Item.new
    @item.images.new # Productクラスのインスタンスに関連づけられた、Imageクラスのインスタンスを作成
    @category_parent_array = ["---"]

    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.roots.pluck(:name).each do |parent|
      @category_parent_array << parent
    end

  end


    # 以下全て、formatはjsonのみ
    # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end


   # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  def create 
    @item = Item.new(item_params)
    @item.status = "0"

    if @images_array.present? && @item.save
      redirect_to root_path, notice: '商品を出品しました'
    else
      # render :new だとViewのカテゴリ選択のところでエラーが発生する
      redirect_to "/items/new", alert: '出品に失敗しました。必須項目を確認してください。'
    end
  end


  def show
    @images = @item.images
    @grandchild = Category.find(@item.category_id)
  end


  def edit
    # データベースから、親カテゴリーのみ抽出し、配列化
    # リファクタリング rootを使うと一気に親まで辿れる
    # pluckを使うことで高速にデータベースから特定カラムのデータを抽出できる
    @category_parent_array = Category.roots.pluck(:name)

    # itemに紐づいていいる孫カテゴリーの親である子カテゴリが属している子カテゴリーの一覧を配列で取得
    @category_child_array = @item.category.parent.parent.children

    # itemに紐づいていいる孫カテゴリーが属している孫カテゴリーの一覧を配列で取得
    @category_grandchild_array = @item.category.parent.children
  end


  def update
    if @item.update(item_params)
      redirect_to root_path, notice: '商品を編集しました'
    else
      redirect_to root_path, alert: '編集できませんでした。必須項目をご確認ください。'
    end
  end


  def destroy
    if @item.user_id == current_user.id && @item.destroy
      redirect_to root_path, notice: '商品を削除しました'
    else
      redirect_to item_path
    end
  end


  private
  # 出品用のストロングパラメータ
  # 値の受け取り制限を設定
  # params.require(モデル名).permit(カラム名, カラム名,...)


  def item_params
    @images_array = params[:item][:images_attributes]
    params.require(:item).permit(:name, :description, :price, :business_result, :category_id, :prefecture_id, :delivery_fee_id, :delivery_way_id, :delivery_day_id, :item_condition_id, :status, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  # def item_update_params
  #   params.require(:item).permit(:name, :detail, :category, :price, :status, :state, :city, :delivery, :delivery_time, :fee_payer).merge(user_id: current_user.id)
  # end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_ease-footer.html.haml
.sell-footer
  .sell-footer__focus-area
    = link_to "プライバシーポリシー", "#", class: "sell-footer__focus-area--atag"
    = link_to "メルカリ利用規約", "#", class: "sell-footer__focus-area--atag"
    = link_to "特定商取引に関する表記", "#", class: "sell-footer__focus-area--atag"
  = link_to image_tag(src= "logo-white.png", size: "185x49", class: "sell-footer__focus-area__image"), "#", class: "sell-container__footer__focus-area__logo"
  .sell-footer__focus-area--text @FURIMA, lnk.

app/views/items/_ease-header.html.haml
.sell-header
  = link_to image_tag(src= "logo.png", size: "185x49"), root_path, class: "sell-header__link"

app/views/items/_footer.html.haml
.appBanner
  .appBanner__inner
    .appBanner__inner--title
      だれでもかんたん、人生を変えるフリマアプリ
    .appBanner__inner--text
      今すぐ無料ダウンロード！
    .appBanner__inner--icon
      = link_to "#", class:"storeLink" do
        .appBanner__inner--icon--apple
          = image_tag "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "storeIcon--a"
      = link_to "#", class:"storeLink" do
        .appBanner__inner--icon--google
          = image_tag "google-play-badge (1).png", class: "storeIcon--g"
.footer
  .footer__contents
    .footer__contents__box
      .footer__contents__box--head
        FURIMAについて
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          会社概要(運営会社)
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          プライバシーポリシー
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          FURIMA利用規約
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          ポイントに関する特約
    .footer__contents__box
      .footer__contents__box--head
        FURIMAを見る
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          カテゴリー一覧
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          ブランド一覧
    .footer__contents__box
      .footer__contents__box--head
        ヘルプ&ガイド
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          FURIMAガイド
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          FURIMAロゴ利用ガイドライン
      .footer__contents__box--list
        = link_to "#", class: "linkFooter" do
          お知らせ
  .footer__logo
    = link_to "#", class:"link" do
      = image_tag "logo-white.png", class:"footer__logo--img"
  .footer__copy
    © FURIMA
= link_to new_item_path, class:"link", data: {"turbolinks" => false} do
  .purchaseBtn
    .purchaseBtn__text
      出品する
      = image_tag "icon_camera.png", class: "purchaseBtn__img"

app/views/items/_header.html.haml
.header
  .header__inner
    .main
      .main__icon
        = link_to root_path do
          = image_tag 'logo.png', class: 'main__icon__image'
      .main__searchBox
        %input.main__searchBox--input{name: "key", placeholder: "キーワードから探す"}
        %button.main__searchBox__submit{type: "submit"}
          = icon("fas", "search", class:"main__searchBox__submit--icon") 
    .naviLists
      .naviLists__Left
        .naviLists__Left--category
          カテゴリー
        .naviLists__Left--brand
          ブランド
      .naviLists__Right
        .naviLists__Right--login

          - if user_signed_in?
            = link_to my_page_path(current_user), class:"link" do
              マイページ
          - else
            = link_to new_user_session_path, class:"link" do
              ログイン
        .naviLists__Right--new
          - if user_signed_in?
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          - else
            = link_to new_user_registration_path, class:"link" do
              新規会員登録

app/views/items/_item.html.haml
// トップページの商品一覧表示用のテンプレート
.listsContent
  .listsContent--img
    = link_to item_path(item), class:"link" do
      = image_tag item.images[0].src.url, alt: "画像無し",size: "220x150", class: 'item-image' if item.images.present?
    - if item.buyer_id.present?
      .item-sold
        SOLD 
    .listsContent__body
      .listsContent__body--name
        = item.name
      .listsContent__body--detail
        .listsContent__body--detail--box
          .listsContent__body--detail--box--price
            = item.price
        .listsContent__body--detail--tax
          (税込)

app/views/items/edit.html.haml
-# 奥本
.sell-container
  =render "ease-header"

  = form_for @item, class:"sell_form" do |f|
    .sell-container__main
      .sell-container__main__inner
        .sell-container__main__inner--head 商品の情報を入力
        .sell-container__main__inner__form
          // ---------------- 画像登録部 ---------------- 
          .sell-container__main__inner__form__upload-box
            .sell-container__main__inner__form__upload-box--head 出品画像
            .alert-text 必須 
            .sell-container__main__inner__form__upload-box--subhead 最大10枚までアップロードできます
            
            .sell-container__main__inner__form__upload-box__drop-area{ id:"image-box" }

              #previews
                - if @item.persisted?
                  - @item.images.each_with_index do |image, i|
                    = image_tag image.src.url, data: { index: i }, width: "100", height: '100'
              .upload-images
                = f.fields_for :images do |image|
                  .js-file_group{"data-index" => "#{image.index}"}
                    = image.file_field :src, class: 'js-file'
                    %br/
                    %span.js-remove 削除
                  - if @item.persisted?
                    = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
                - if @item.persisted?
                  .js-file_group{"data-index" => "#{@item.images.count}"}
                    = file_field_tag :src, name: "item[images_attributes][#{@item.images.count}][src]", class: 'js-file'
                    .js-remove 削除

          // ---------------- タイトルと説明入力部 ----------------
          .sell-container__main__inner__form__input1
            .sell-container__main__inner__form__input1--title 商品名
            .alert-text 必須 
            = f.text_field :name, class: 'sell-container__main__inner__form__input1--title-default', placeholder: '商品名（必須 40文字まで)'

            .sell-container__main__inner__form__input1--desc 商品の説明
            .alert-text 必須
            = f.text_area :description, class: 'sell-container__main__inner__form__input1--desc-default', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。',rows:"5"

          -# // ---------------- 詳細入力部 ----------------
          .sell-container__main__inner__form__input2
            .sell-container__main__inner__form__input2--sub-title 商品の詳細
            .sell-container__main__inner__form__input2__form-box.clearfix
              .sell-container__main__inner__form__input2__form-box__group1

                .listing-form-box
                  .listing-product-detail__category
                    = f.label 'カテゴリー', class: 'sell-container__main__inner__form__input2__form-box__group1--input-title'
                    .alert-text 必須
                    .listing-select-wrapper
                      .listing-select-wrapper__box
                        = f.select :category_id, options_for_select(@category_parent_array.map{|c|[c, {}]}, @item.category.root.name), {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category_edit'}
                        .form_group#children
                          = f.select :category_id, options_for_select(@category_child_array.map{|c|[c[:name], c[:id], {'data-category'=>c[:id], 'id'=>c[:id]}]}, @item.category.parent.id), {}, {class: 'listing-select-wrapper__box--select', id: 'child_category_edit'}
                        .form_group#grandchildren
                          = f.select :category_id, options_for_select(@category_grandchild_array.map{|c|[c[:name], c[:id], {'data-category'=>c[:id], 'id'=>c[:id]}]}, @item.category.id), {}, {class: 'listing-select-wrapper__box--select', id: 'grandchild_category_edit'}
                        = f.text_field :category_id, id: 'grand_child_result_id', type: 'hidden'

                        -# --------------------- Ajax通信の流れ -----------------------------
                        -# ユーザーが親カテゴリが変更する
                        -# JavaScriptのchangeイベントが呼ばれる
                        -# JavaScriptがサーバーに子カテゴリの一覧を問い合わせる
                        -# サーバーが子カテゴリの一覧をJSONで返す
                        -# JavaScriptがサーバーから子カテゴリの一覧を受け取る
                        -# 子カテゴリセレクトボックスの中身をサーバーから受け取った子カテゴリの一覧で置き換える
                        -# -----------------------------------------------------------------

              .sell-container__main__inner__form__input2__form-box__group2
                .sell-container__main__inner__form__input2__form-box__group2--input-title 商品の状態
                .alert-text 必須
                = f.collection_select :item_condition_id, ItemCondition.all, :id, :name, prompt: "---"

          -# // ---------------- 配送情報入力部 ---------------- 
          .sell-container__main__inner__form__input3
            .sell-container__main__inner__form__input3--sub-title 配送について
            .form-question ?
            .sell-container__main__inner__form__input3__form-box.clearfix
              .sell-container__main__inner__form__input3__form-box__group1
                .sell-container__main__inner__form__input3__form-box__group1--input-title 配送料の負担
                .alert-text 必須
                = f.collection_select :delivery_fee_id, DeliveryFee.all, :id, :name, prompt: "---"

              .sell-container__main__inner__form__input3__form-box__group2
                .sell-container__main__inner__form__input3__form-box__group2--input-title 発送の方法
                .alert-text 必須
                = f.collection_select :delivery_way_id, DeliveryWay.all, :id, :name, prompt: "---"

              .sell-container__main__inner__form__input3__form-box__group2
                .sell-container__main__inner__form__input3__form-box__group2--input-title 発送元の地域
                .alert-text 必須
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "---"

              .sell-container__main__inner__form__input3__form-box__group2
                .sell-container__main__inner__form__input3__form-box__group2--input-title 発送までの日数
                .alert-text 必須
                = f.collection_select :delivery_day_id, DeliveryDay.all, :id, :name, prompt: "---"

          -# // ---------------- 販売価格入力部 ---------------- 
          .sell-container__main__inner__form__input4
            .sell-container__main__inner__form__input4--sub-title 販売価格(¥300~9,999,999)
            .form-question ?
            .sell-container__main__inner__form__input4__form-box.clearfix
              .sell-container__main__inner__form__input4__form-box__group1
                .sell-container__main__inner__form__input4__form-box__group1__left
                  .sell-container__main__inner__form__input4__form-box__group1__left--input-title 価格
                  .alert-text 必須
                .sell-container__main__inner__form__input4__form-box__group1__right
                  = f.number_field :price, class:'input-price', id:"price_calc", placeholder: '例) 300'
              .sell-container__main__inner__form__input4__form-box__group2
                .sell-container__main__inner__form__input4__form-box__group2--handling-title 販売手数料(10%)
                .sell-container__main__inner__form__input4__form-box__group2--handling-cost
                  .right_bar
              .sell-container__main__inner__form__input4__form-box__group2
                .sell-container__main__inner__form__input4__form-box__group2--profit-title 販売利益
                .sell-container__main__inner__form__input4__form-box__group2--profit
                  = f.number_field :business_result, style: "display: none", id: "price"
                  .right_bar_2


          .sell-container__main__inner__form__sell-btn-box
            .sell-container__main__inner__form__sell-btn-box--caution-text
              = link_to "禁止されている出品", "#", class: "caution-text-a-tag"
              、
              = link_to "行為", "#", class: "caution-text-a-tag"
              を必ずご確認ください。
              %br
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "偽ブランドの販売", "#", class: "caution-text-a-tag"
              は犯罪であり処罰される可能性があります。
              また、出品をもちまして
              = link_to "加盟店規約", "#", class: "caution-text-a-tag"
              に同意したことになります。

            = f.submit "変更する", class:"sell-container__main__inner__form__sell-btn-box__submit-btn"

            .sell-container__main__inner__form__sell-btn-box__back-btn
              = link_to "キャンセル", root_path, class: "sell-back-btn"

  =render "ease-footer"

app/views/items/index.html.haml
.notice.text-style
  - if flash[:notice]
    %p= flash[:notice]
    
.alert.text-style
  - if flash[:alert]
    %p= flash[:alert]

= render "header"

.mainImage
  .mainImage__content
    .mainImage__content__subtitle
      人生を変えるフリマアプリ
    .mainImage__content__text
      FURIMAはだれでもかんたんに出品・購入できる
      %br
      フリマアプリです
    .mainImage__content__btn
      = link_to "#", class:"storeLink" do
        .mainImage__content__btn--apple
          = image_tag 'Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg', class: "storeIcon--a"
      = link_to "#", class:"storeLink" do
        .mainImage__content__btn--google
          = image_tag 'google-play-badge (1).png', class: "storeIcon--g"
.introduction
  .introduction__subtitle
    FURIMAが選ばれる3つの理由
  .introduction__lists
    .introduction__lists__box
      .introduction__lists__box--img
        .number
          1
        = image_tag 'pict-reason-01.jpg', class:"img"
      .introduction__lists__box--text
        .introduction__lists__box--text--color
          3分
        ですぐに出品
      .introduction__lists__box--discription
        スマホで入力するだけで簡単に出品できる！
    .introduction__lists__box
      .introduction__lists__box--img
        .number
          2
        = image_tag 'pict-reason-02.jpg', class:"img"
      .introduction__lists__box--text
        .introduction__lists__box--text--color
          シンプル
        で使いやすい
      .introduction__lists__box--discription
        めんどくさい入力は必要なく、検索も購入もスムーズ！
    .introduction__lists__lastBox
      .introduction__lists__lastBox--img
        .number
          3
        = image_tag 'pict-reason-03.jpg', class:"img"
      .introduction__lists__lastBox--text
        手数料
        .introduction__lists__lastBox--text--color
          業界最安値
      .introduction__lists__lastBox--discription
        最大3%でお得に出品&購入！

.middleImage
  .middleImage__inner
    .middleImage__inner__subtitle
      会員数日本一位
    .middleImage__inner__text
      FURIMAはフリマアプリで最も人気。
      %br
      出品、購入回数も業界最多です！
      %br
      ほしかったあの商品にも出会えるかもしれません。
    .middleImage__inner__btn
      = link_to "#", class:"storeLink" do
        .middleImage__inner__btn--apple
          = image_tag 'Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg', class: "storeIcon--a"
      = link_to "#", class:"storeLink" do
        .middleImage__inner__btn--google
          = image_tag 'google-play-badge (1).png', class: "storeIcon--g"

.feature
  .feature__subtitle
    FURIMAの特徴
  .feature__lists
    .feature__lists__box
      .feature__lists__box--img
        = image_tag 'icon-01.png', class: "feature__img"
      .feature__lists__box--text
        簡単に売り買いできる
      .feature__lists__box--discription
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能
    .feature__lists__box
      .feature__lists__box--img
        = image_tag 'icon-03.png', class: "feature__img"
      .feature__lists__box--text
        売上金は即日振込みに対応
      .feature__lists__box--discription
        午前9時までに振込を依頼いただければ、翌日に指定の口座に入金致します。
    .feature__lists__box
      .feature__lists__box--img
        = image_tag 'icon-04.png', class: "feature__img"
      .feature__lists__box--text
        様々な支払いに対応
      .feature__lists__box--discription
        お支払いはクレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

.pickupItem
  .pickupItem__head
    ピックアップカテゴリー
  .pickupItem__box
    .pickupItem__box__head
      .pickupItem__box__head--title
        新規投稿商品
    .pickupItem__box__lists
      = render @items
      
= render "items/footer" 

app/views/items/show.html.haml
-# 高橋さん担当
=render "header"

.main-content
  .main-content__box
    .item-name
      = @item.name
      - if @item.buyer_id.present?
        .item-sold__width
          SOLD

    .item-main-content
      %ul.item-main-content__photo
        = image_tag @images.first.src.url, alt: '商品画像', size: "300x300" ,class: "item-image-main" if @images.present?
        %li.photo-up-piece
          - @item.images.each_with_index do |image, i|
            = image_tag image.src.url, size:"60x60", class:"item-image-lists", data: { index: i }

       
      
      %table.item-main-content__table
        %tbody
          %tr
            %th.text-style 出品者
            %td
              = @item.user.nickname
          %tr
            %th カテゴリー
            %td.category-names.text-style
              = @grandchild.parent.parent.name
              %br
              %i.fa.fa-angle-right
              = @grandchild.parent.name
              %br
              %i.fa.fa-angle-right
              = @grandchild.name
          %tr
            %th.text-style 商品の状態
            %td.text-style 
              = @item.item_condition.name
          %tr
            %th.text-style 配送料の負担
            %td.text-style
              = @item.delivery_fee.name
          %tr
            %th.text-style 配送元地域
            %td.text-style
              = @item.prefecture.name
          %tr
            %th.text-style 発送日の目安
            %td.text-style
              = @item.delivery_day.name

    .item-price-box
      .item-price-box__price
        = number_to_currency(@item.price, unit: "￥", strip_insignificant_zeros: true)
      .item-price-box__tax
        (税込)
      .item-price-box__shipping-fee
        送料込み
      
    .item-buy-link
      -if user_signed_in? && current_user.id == @item.user_id
        = link_to '商品の編集', edit_item_path(@item.id), class:'item-buy-link__btn', data: {"turbolinks" => false}
        = link_to '商品の削除', item_path(@item.id), method: :delete, data: {confirm: '削除してよろしいですか？'} ,class:'item-buy-link__btn--delete'
      -elsif user_signed_in? && @item.buyer_id == nil
        = link_to '購入画面に進む', item_purchase_index_path(@item.id), class:'item-buy-link__btn', data: {"turbolinks" => false}
      - else
        = link_to "戻る", root_path, class: 'item-buy-link__btn'
    .item-description 
      .item-description__box
        = @item.description
       
  .main-content__comment
    .comment__message
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .comment__box
      %textarea.comment__box--text{type: "text"}
      = link_to 'コメントする', '#', class:'coment_btn'

  %ul.main-content__links
    %li
      = link_to '#' do
        %i.fa.fa-angle-left
        前の商品
    %li
      = link_to '#' do
        後ろの商品
        %i.fa.fa-angle-right

= render "footer"