config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root "items#index"

  resources :cards, only: [:new, :create, :edit, :show, :destroy, :update]
  
  resources :my_pages, only: [:show]

  resources :items do
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  # has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/delivery_day.rb
class DeliveryDay < ActiveHash::Base
  self.data = [
                {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
              ]
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
                {id: 1, name: '送料込み（配送者負担）'}, {id: 2, name: '着払い（購入者負担）'}
              ]
end

app/models/delivery_style.rb
class DeliveryStyle < ApplicationRecord
  # has_many :items
end

app/models/delivery_way.rb
class DeliveryWay < ActiveHash::Base
  self.data = [
                {id: 1, name: '未定'}, {id: 2, name: 'らくらくメルカリ便'}, {id: 3, name: 'ゆうメール'},
                {id: 4, name: 'レターパック'}, {id: 5, name: '普通郵便（定形、定形外'}, {id: 6, name: 'クロネコヤマト'},
                {id: 7, name: 'ゆうパック'}, {id: 8, name: 'クリックポスト'}, {id: 9, name: 'ゆうパケット'}
              ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader  :src  , ImageUploader
  belongs_to      :item , optional: true
  validates       :item , presence: true, on: :update # on :updateはupdateアクションの時のみにバリデーション検証が実行されるもの
  validates       :src  , presence: true, on: :update 
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  belongs_to :category, optional: true #nullを許可

  belongs_to :user


  # fields_forメソッドを利用する際に、親モデルの中に書く必要があるメソッド。引数として子モデルの名前を書く。
  # allow_destroy: trueで親のレコードが削除された場合に、関連付いている子のレコードも一緒に削除してくれます
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank

  validates :name,               presence: true, length: { maximum: 40 }
  validates :description,        presence: true, length: { maximum: 1000 }
  validates :price,              presence: true, numericality: { only_integr: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :business_result,    presence: true
  validates :category_id,        presence: true
  validates :prefecture_id,      presence: true
  validates :delivery_fee_id,    presence: true
  validates :delivery_way_id,    presence: true
  validates :delivery_day_id,    presence: true
  validates :item_condition_id,  presence: true
  validates :status,             presence: true
  validates :images,             presence: true, on: :update # on :updateはupdateアクションの時のみにバリデーション検証が実行されるもの
  

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :delivery_way
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_day
  belongs_to_active_hash :item_condition

  

end

app/models/item_condition.rb
class ItemCondition < ActiveHash::Base
  self.data = [
                {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れ無し'},
                {id: 4, name: 'やや傷や汚れ有り'}, {id: 5, name: '傷や汚れ有り'}, {id: 6, name: '全体的に状態が悪い'}
              ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :email, presence: true
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true
  validates :birthday, presence: true

   # 半角以外の正規表現      
  validates :family_name, :first_name,format: {
    with: /[^ -~｡-ﾟ]+/,
    message: "全角のみで入力して下さい"
  }

  validates :family_name_kana, :first_name_kana,format: {
    with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/,
    message: "全角カタカナのみで入力して下さい"
  }


  has_many :items

  has_one :card

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user) if card.exists?
  end


  def create  #payjpとCardのデータベース作成
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', 
      email: current_user.email, 
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(current_user)
      else
        redirect_to action: "create"
      end
    end
  end


  def show  #Cardのデータをpayjpに送り情報取り出す
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end  
  end

  def destroy
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end


  private

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end
  
  
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/cards/_footer.html.haml
-# フッターは共通
.sell-container__footer
  .sell-container__footer__focus-area
    = link_to "プライバシーポリシー", "#", class: "sell-container__footer__focus-area--atag"
    = link_to "メルカリ利用規約", "#", class: "sell-container__footer__focus-area--atag"
    = link_to "特定商取引に関する表記", "#", class: "sell-container__footer__focus-area--atag"
    = link_to image_tag(src= "logo-white.png", size: "185x49", class: "sell-container__footer__focus-area__image"), "#", class: "sell-container__footer__focus-area__logo"
    .sell-container__footer__focus-area--text @FURIMA, lnk.

app/views/cards/_form.html.haml
.card-container__label
  %label カード番号
  .alert-text 必須
  = text_field_tag "number", "", class: "card_number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
    
.card-container__label
  %label 有効期限
  .alert-text 必須
  .select__box.top__margin
    .select__box__half
      %select#exp_month{name: "exp_month", type: "text"}
        %option{value: ""} --
        %option{value: "1"}01
        %option{value: "2"}02
        %option{value: "3"}03
        %option{value: "4"}04
        %option{value: "5"}05
        %option{value: "6"}06
        %option{value: "7"}07
        %option{value: "8"}08
        %option{value: "9"}09
        %option{value: "10"}10
        %option{value: "11"}11
        %option{value: "12"}12
      %i
      %span 月
    .select__box__half
      %select#exp_year{name: "exp_year", type: "text"}
        %option{value: ""} --
        %option{value: "2019"}19
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
      %i
      %span  年

.card-container__label
  %label セキュリティーコード
  .alert-text 必須
  .card-text
    ※カード背面4桁もしくは3桁の番号
  = text_field_tag "cvc", "", class: "cvc", placeholder: "4桁もしくは3桁の番号", maxlength: "4", id: "cvc"

app/views/cards/_header.html.haml
-# ヘッターは共通
.sell-container
  .sell-container__header
    = link_to image_tag(src= "logo.png", size: "185x49"), items_path, class: "sell-container__header__link"

app/views/cards/new.html.haml
= render "header"

.card-main
  .card-container
    .card-container__title
      クレジットカード情報入力
    .card-container__label
      = form_tag(cards_path, method: :post, action: "create", id: 'charge-form',  name: "inputForm") do
        .card-container__label
          %label カード番号
          .alert-text 必須
          = text_field_tag "number", "", class: "card_number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            
        .card-container__label
          %label 有効期限
          .alert-text 必須
          .select__box.top__margin
            .select__box__half
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %i
              %span 月
            .select__box__half
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %i
              %span  年

        .card-container__label
          %label セキュリティーコード
          .alert-text 必須
          .card-text
            ※カード背面4桁もしくは3桁の番号
          = text_field_tag "cvc", "", class: "cvc", placeholder: "4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
        #card_token
          = submit_tag "登録する", id: "token_submit", class: "top__margin"
      
= render "footer"

app/views/cards/show.html.haml
= render "header"

.card-main
  .card-container
    .card-container__title
      支払い方法
    .card-container__label
      %label 登録クレジットカード情報
      %br
      = "**** **** **** " + @default_card_information.last4
      %br
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      = exp_month + " / " + exp_year

    .card-container__btn
      = form_tag(card_path, method: :delete, id: 'charge-form',  name: "inputForm") do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button.card-delete-btn 削除する

      = link_to "マイページへ戻る", my_page_path(current_user), class:"back-btn"

= render "footer"